### ISSUE TITLE
Is this a plover addon?

### ISSUE THREAD

**Issue by Zireael07** [jxcrw/sphk#1]
README isn't clear

**Comment by jak-crow** [comment]
Nope! It's a custom steno theory designed for custom steno hardware, and I'm using a hacked version of Plover as the backend steno "engine" (i.e., to translate chords into words).

Right now I mainly have this repo public on my Github account to use as a portfolio project for software engineering interviews, and to share/sync my steno dictionaries between computers. It's not currently my intention to bring the documentation/custom build of Plover up to a level that's suitable for general-purpose use by other people, although there's a (small) chance that I might do so at some unspecified time in the (distant) future.

Apologies to disappoint if you were interested in using this yourself, but thank you for the issue :) !
